name = "Fractalide"
license = "MIT"
licenselink = "https://github.com/fractalide/fractalide-website-styx/blob/master/fractalide-hugo-theme/LICENSE"
description = "A port of the Universal theme"
homepage = "//github.com/fractalide/fractalide-website-styx"
tags = ["blog", "company", "minimal", "responsive"]
features = ["blog", "disqus", "minimal", "responsive"]
min_version = 0.21

[author]
    name = "fractalide"
    homepage = "//github.com/fractalide"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "//github.com/devcows/hugo-universal-theme"

